spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/defi_project
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    locations: classpath:db/migration
server:
  port: 8080